### ISSUE TITLE
partial matches

### ISSUE THREAD

**Issue by comfysquirrel** [lasercar/SimpleMention#8]
eg `@jon` will find `@_jon_`

**Comment by comfysquirrel** [comment]
what to do if multiple matches are found?

**Comment by comfysquirrel** [comment]
just mention both people

**Comment by lasercar** [comment]
if exact username/nickname match, don't mention others (to prevent `@jon` from unavoidably pinging `@_jon_`). but non-exact matches like `@jo` will still mention both.

**Comment by comfysquirrel** [comment]
Core done, but see #15
